# Generated by Django 4.2.27 on 2026-08-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('vers', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version')),
            ],
            options={
                'unique_together': {('vers', 'prog'), ('vers', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AtomsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('mutex', models.BooleanField(default=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.attribute')),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version')),
            ],
            options={
                'unique_together': {('vers', 'attr', 'prog'), ('vers', 'attr', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('type', models.TextField()),
                ('args', models.JSONField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('attr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.attribute')),
                ('deny', models.ManyToManyField(related_name='revdeny', to='django_gem_taxonomy.atom')),
                ('deps', models.ManyToManyField(related_name='revdeps', to='django_gem_taxonomy.atom')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.atomsgroup')),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version')),
            ],
            options={
                'unique_together': {('vers', 'name'), ('vers', 'attr', 'group', 'prog')},
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('atom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.atom')),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version')),
            ],
            options={
                'unique_together': {('vers', 'atom', 'name'), ('vers', 'atom', 'prog')},
            },
        ),
    ]
