# Generated by Django 4.2.27 on 2026-05-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='deny',
            field=models.ManyToManyField(related_name='revdeny', to='django_gem_taxonomy.atom'),
        ),
        migrations.AlterField(
            model_name='param',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
