# Generated by Django 4.2.30 on 2026-09-01 15:15

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0002_versrelatedcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
