# Generated by Django 4.2.30 on 2026-09-22 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0002_atom_deny_alter_param_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version2',
            fields=[
                ('vers', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version2')),
            ],
            options={
                'unique_together': {('vers', 'name'), ('vers', 'prog')},
            },
        ),
        migrations.CreateModel(
            name='AtomsGroup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('mutex', models.BooleanField(default=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.attribute2')),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version2')),
            ],
            options={
                'unique_together': {('vers', 'attr', 'name'), ('vers', 'attr', 'prog')},
            },
        ),
        migrations.CreateModel(
            name='Atom2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('type', models.TextField()),
                ('args', models.JSONField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('attr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.attribute2')),
                ('deny', models.ManyToManyField(related_name='revdeny', to='django_gem_taxonomy.atom2')),
                ('deps', models.ManyToManyField(related_name='revdeps', to='django_gem_taxonomy.atom2')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.atomsgroup2')),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version2')),
            ],
            options={
                'unique_together': {('vers', 'attr', 'group', 'prog'), ('vers', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Param2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prog', models.IntegerField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('atom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.atom2')),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.version2')),
            ],
            options={
                'unique_together': {('vers', 'atom', 'name'), ('vers', 'atom', 'prog')},
            },
        ),
    ]
