# Generated by Django 4.2.30 on 2026-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0003_alter_content_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='versrelatedcontent',
            unique_together={('vers', 'name')},
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_generic_relation'),
        ),
    ]
