# Generated by Django 4.2.30 on 2026-09-22 22:39
from django.db import migrations

def dgtaxonomy2dgtaxonomy_two(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Attribute= apps.get_model("django_gem_taxonomy", "Attribute")
    AtomsGroup= apps.get_model("django_gem_taxonomy", "AtomsGroup")
    Atom= apps.get_model("django_gem_taxonomy", "Atom")
    Param= apps.get_model("django_gem_taxonomy", "Param")
    Version2= apps.get_model("django_gem_taxonomy", "Version2")
    Attribute2= apps.get_model("django_gem_taxonomy", "Attribute2")
    AtomsGroup2= apps.get_model("django_gem_taxonomy", "AtomsGroup2")
    Atom2= apps.get_model("django_gem_taxonomy", "Atom2")
    Param2= apps.get_model("django_gem_taxonomy", "Param2") 

    # migrate to the new schema that includes version as part of the
    # unique constraints, the old version has '4.0' as implied

    if Attribute.objects.using(db_alias).all().count() == 0:
        return

    try:
        vers = Version2.objects.using(db_alias).get(vers='4.0')
    except Version2.DoesNotExist:
        vers = Version2.objects.using(db_alias).create(
            vers='4.0',
            desc='Version 4.0 year 2025',
            is_default=True
        )

    for attr_in in Attribute.objects.using(db_alias).all():
        attr = Attribute2.objects.using(db_alias).create(
                vers=vers,
                name=attr_in.name,
                prog=attr_in.prog,
                title=attr_in.title,
            )

    for atg_in in AtomsGroup.objects.using(db_alias).all():
        AtomsGroup2.objects.using(db_alias).create(
                vers=vers,
                name=atg_in.name,
                prog=atg_in.prog,
                title=atg_in.title,
                mutex=atg_in.mutex,
                attr=Attribute2.objects.using(db_alias).get(vers=vers, name=atg_in.attr.name)
            )
   
    for at_in in Atom.objects.using(db_alias).all():
        if at_in.attr is not None:
            attr = Attribute2.objects.using(db_alias).get(vers=vers, name=at_in.attr.name)
        else:
            attr = None

        if at_in.group is not None:
            group = AtomsGroup2.objects.using(db_alias).get(vers=vers, attr=attr,
                                                            name=at_in.group.name)
        else:
            group = None
        
        atom = Atom2.objects.using(db_alias).create(
            vers=vers,
            name=at_in.name,
            prog=at_in.prog,
            title=at_in.title,
            desc=at_in.desc,
            args=at_in.args,
            params=at_in.params,
            type=at_in.type,
            attr=attr,
            group=group,
        )

    for at_in in Atom.objects.using(db_alias).all():
        atom = Atom2.objects.using(db_alias).get(vers=vers, name=at_in.name)
        for dep in at_in.deps.all():
            atom.deps.add(Atom2.objects.using(db_alias).get(vers=vers, name=dep.name))
        for den in at_in.deny.all():
            atom.deny.add(Atom2.objects.using(db_alias).get(vers=vers, name=den.name))

    for par_in in Param.objects.using(db_alias).all():
        Param2.objects.using(db_alias).create(
            vers=vers,
            atom=Atom2.objects.using(db_alias).get(vers=vers, name=par_in.atom.name),
            name=par_in.name,
            title=par_in.title,
            desc=par_in.desc,
            prog=par_in.prog,
        )

def dgtaxonomy_two2dgtaxonomy(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Attribute= apps.get_model("django_gem_taxonomy", "Attribute")
    AtomsGroup= apps.get_model("django_gem_taxonomy", "AtomsGroup")
    Atom= apps.get_model("django_gem_taxonomy", "Atom")
    Param= apps.get_model("django_gem_taxonomy", "Param")
    Version2= apps.get_model("django_gem_taxonomy", "Version2")
    Attribute2= apps.get_model("django_gem_taxonomy", "Attribute2")
    AtomsGroup2= apps.get_model("django_gem_taxonomy", "AtomsGroup2")
    Atom2= apps.get_model("django_gem_taxonomy", "Atom2")
    Param2= apps.get_model("django_gem_taxonomy", "Param2") 

    try:
        vers = Version2.objects.using(db_alias).get(vers='4.0')
    except Version2.DoesNotExist:
        return

    Param.objects.using(db_alias).delete()
    Atom.objects.using(db_alias).delete()
    AtomsGroup.objects.using(db_alias).delete()
    Attribute.objects.using(db_alias).delete()

    for attr_in in Attribute2.objects.using(db_alias).filter(vers=vers):
        attr = Attribute.objects.using(db_alias).create(
            name=attr_in.name,
            prog=attr_in.prog,
            title=attr_in.title,
        )

    for atg_in in AtomsGroup2.objects.using(db_alias).filter(vers=vers):
        AtomsGroup.objects.using(db_alias).create(
                name=atg_in.name,
                prog=atg_in.prog,
                title=atg_in.title,
                mutex=atg_in.mutex,
                attr=Attribute.objects.using(db_alias).get(name=atg_in.attr.name)
            )
    for at_in in Atom2.objects.using(db_alias).filter(vers=vers):
        if at_in.attr is not None:
            attr = Attribute.objects.using(db_alias).get(name=at_in.attr.name)
        else:
            attr = None

        if at_in.group is not None:
            group = AtomsGroup.objects.using(db_alias).get(attr=attr,
                                                           name=at_in.group.name)
        else:
            group = None
        
        atom = Atom.objects.using(db_alias).create(
            name=at_in.name,
            prog=at_in.prog,
            title=at_in.title,
            desc=at_in.desc,
            args=at_in.args,
            params=at_in.params,
            type=at_in.type,
            attr=attr,
            group=group,
        )

    for at_in in Atom2.objects.using(db_alias).filter(vers=vers):
        atom = Atom.objects.using(db_alias).get(name=at_in.name)
        for dep in at_in.deps.all():
            atom.deps.add(Atom.objects.using(db_alias).get(name=dep.name))
        for den in at_in.deny.all():
            atom.deny.add(Atom.objects.using(db_alias).get(name=den.name))

    for par_in in Param2.objects.using(db_alias).filter(vers=vers):
        Param.objects.using(db_alias).create(
            atom=Atom.objects.using(db_alias).get(name=par_in.atom.name),
            name=par_in.name,
            title=par_in.title,
            desc=par_in.desc,
            prog=par_in.prog,
        )

    Param2.objects.using(db_alias).delete()
    Atom2.objects.using(db_alias).delete()
    AtomsGroup2.objects.using(db_alias).delete()
    Attribute2.objects.using(db_alias).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0003_version2_attribute2_atomsgroup2_atom2_param2'),
    ]

    operations = [
        migrations.RunPython(dgtaxonomy2dgtaxonomy_two, dgtaxonomy_two2dgtaxonomy)
    ]
