# Generated by Django 4.2.30 on 2026-09-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0004_content_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Param',
        ),
        migrations.DeleteModel(
            name='Atom',
        ),
        migrations.DeleteModel(
            name='AtomsGroup',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
