# Generated by Django 4.2.30 on 2026-09-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0005_remove_old_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Version2',
            new_name='Version',
        ),
        migrations.RenameModel(
            old_name='Attribute2',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='AtomsGroup2',
            new_name='AtomsGroup',
        ),
        migrations.RenameModel(
            old_name='Atom2',
            new_name='Atom',
        ),
        migrations.RenameModel(
            old_name='Param2',
            new_name='Param',
        ),
    ]
