# Generated by Django 4.2.30 on 2026-09-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gem_taxonomy', '0006_rename_new_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='atom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gem_taxonomy.atom'),
        ),
    ]
