name: Test Django Package

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools
        pip install -U pip

        if [ "$BRANCH_NAME" != "main" ]; then
          # django-gem-taxonomy doesn't depend directly from oq-gem-taxonomy-data so to mantain all consistent we
          #   must install ...-data package independently and before oq-gem-taxonomy dependencies resolution
          if [ "$(git ls-remote --heads https://github.com/gem/oq-gem-taxonomy-data.git "refs/heads/${BRANCH_NAME}")" != "" ]; then
            pip install "openquake.gem-taxonomy-data@git+https://github.com/gem/oq-gem-taxonomy-data.git@${BRANCH_NAME}"
         fi
         if [ "$(git ls-remote --heads https://github.com/gem/oq-gem-taxonomy.git "refs/heads/${BRANCH_NAME}")" != "" ]; then
            sed -i "s|'openquake.gem-taxonomy .*|'openquake.gem-taxonomy @ git+https://github.com/gem/oq-gem-taxonomy.git@${BRANCH_NAME}',|g" pyproject.toml
                echo "=== modified pyproject.toml ==="
                cat pyproject.toml
                echo "=== end ==="
            fi
        fi

        pip install '.[test]'
    - name: Run tests
      run: |
        python -m pytest

