name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Keys Ingestion
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        cat  >> ~/.ssh/config << EOF

        Host oq-gem-taxonomy-host
        Hostname github.com
        User git
        StrictHostKeyChecking no
        IdentityFile ~/.ssh/id_oq-gem-taxonomy
        IdentitiesOnly yes

        Host oq-gem-taxonomy-data-host
        Hostname github.com
        User git
        StrictHostKeyChecking no
        IdentityFile ~/.ssh/id_oq-gem-taxonomy-data
        IdentitiesOnly yes
        EOF

        git config --global url."ssh://git@oq-gem-taxonomy-host/gem/oq-gem-taxonomy.git".insteadOf "ssh://git@github.com/gem/oq-gem-taxonomy.git"
        git config --global url."ssh://git@oq-gem-taxonomy-data-host/gem/oq-gem-taxonomy-data.git".insteadOf "ssh://git@github.com/gem/oq-gem-taxonomy-data.git"

        base64 -d <<< ${{ secrets.OQ_GEM_TAXONOMY_KEY }} > ~/.ssh/id_oq-gem-taxonomy
        chmod 600 ~/.ssh/id_oq-gem-taxonomy
        base64 -d <<< ${{ secrets.OQ_GEM_TAXONOMY_DATA_KEY }} > ~/.ssh/id_oq-gem-taxonomy-data
        chmod 600 ~/.ssh/id_oq-gem-taxonomy-data

    - name: Install dependencies
      run: |
        pip install '.[test]'
    - name: Run tests
      run: |
        python -m pytest

